import type { Metadata } from 'next'
import Link from 'next/link'
import Reveal from '@/components/motion/reveal'
import Header from '@/components/header'
import Footer from '@/components/footer'
import Stewardship from '@/components/stewardship'
import StartupVirginia from '@/components/startup-virginia'
import CustomerDiscovery from '@/components/customer-discovery'

export const metadata: Metadata = {
  title: 'About — Why TopoStitch exists',
  description: 'Jacob Galito’s path from product design and cultural-heritage AR to persistent contextual records for physical objects and places.',
}

export default function AboutPage() {
  return <><Header /><main id="main-content" className="pt-16">
    <section className="mx-auto max-w-4xl px-4 py-16 sm:px-6 md:py-24 lg:px-8">
      <Reveal><p className="text-sm font-medium text-muted-foreground">About TopoStitch</p></Reveal>
      <Reveal delay={0.08}><h1 className="mt-5 text-balance text-4xl font-medium leading-tight md:text-5xl">Why TopoStitch exists</h1></Reveal>
      <Reveal delay={0.16}><p className="mt-7 text-xl leading-relaxed text-muted-foreground">TopoStitch preserves the knowledge surrounding physical cultural heritage, not merely the files used to represent it. That mission grew from a recurring problem in the work of founder Jacob Galito.</p></Reveal>
      <div className="mt-12 space-y-12">
        <section className="space-y-5"><Reveal><h2 className="text-2xl font-medium md:text-3xl">A career connecting digital experiences to physical things</h2></Reveal><Reveal><p className="leading-relaxed text-muted-foreground">Across nearly two decades of product design, 3D, immersive technology, and spatial computing, Jacob has built digital experiences around real objects and environments. His work spans AR and VR products, enterprise and industrial applications, defense, training, museums, and cultural heritage.</p></Reveal><Reveal><p className="leading-relaxed text-muted-foreground">Before starting TopoStitch, he co-founded immersive technology company Ario and served as its Creative Director. He was a co-inventor on Ario’s patented platform. Building a startup and bringing spatial tools into professional workflows shaped his understanding of the distance between a compelling demonstration and a system that people can use over time.</p></Reveal></section>
        <section className="space-y-5"><Reveal><h2 className="text-2xl font-medium md:text-3xl">Cultural heritage made the context tangible</h2></Reveal><Reveal><h3 className="text-xl font-medium">Old Dominion University’s Barry Art Museum</h3></Reveal><Reveal><p className="leading-relaxed text-muted-foreground">During the mask-mandate period, cultural institutions were exploring new ways to connect audiences with physical collections and spaces through digital experiences. Jacob created an augmented reality experience for the Barry Art Museum, bringing his spatial-design practice into that setting.</p></Reveal><Reveal><h3 className="text-xl font-medium">White House Historical Association</h3></Reveal><Reveal><p className="leading-relaxed text-muted-foreground">Jacob also created two augmented reality experiences for the White House Historical Association. These projects connected historic places and objects with interpretation and digital storytelling. The spatial representation was one part of the experience; the history and knowledge around it gave it meaning.</p></Reveal><Reveal><p className="text-sm leading-relaxed text-muted-foreground">These projects belong to Jacob’s prior professional experience and are not TopoStitch institutional partnerships.</p></Reveal></section>
        <section className="space-y-5"><Reveal><h2 className="text-2xl font-medium md:text-3xl">Experience beyond the exhibition</h2></Reveal><Reveal><p className="leading-relaxed text-muted-foreground">Jacob’s prior professional and Ario work included projects connected to Dominion Energy, BAE Systems, the U.S. Air Force, the U.S. Army, and Huntington Ingalls Industries. Those settings brought enterprise workflows, operational constraints, and the needs of different contributors into view.</p></Reveal><Reveal><ul className="space-y-3 rounded-xl border border-border bg-muted/20 p-6"><li>NATO Innovation Challenge — 1st Place</li><li>Verizon 5G Challenge — 1st Place</li></ul></Reveal><Reveal><p className="text-sm leading-relaxed text-muted-foreground">These recognitions relate to Jacob’s prior Ario experience. The organizations above are not presented as TopoStitch customers.</p></Reveal></section>
        <section aria-labelledby="lived-experience-title" className="space-y-5">
          <Reveal><h2 id="lived-experience-title" className="text-2xl font-medium md:text-3xl">Built from lived experience</h2></Reveal>
          <Reveal><p className="leading-relaxed text-muted-foreground">TopoStitch is an LGBTQ+-, Filipino American-, and veteran-owned technology company based in Richmond, Virginia.</p></Reveal>
          <Reveal><p className="leading-relaxed text-muted-foreground">Founder Jacob Galito served for 12 years in the U.S. Navy, including eight years on active duty, before continuing his career across product design, immersive technology, 3D, AR/VR, and spatial computing.</p></Reveal>
          <Reveal><p className="leading-relaxed text-muted-foreground">His work with the Barry Art Museum and the White House Historical Association, alongside co-founding Ario, serving as its Creative Director, and becoming a co-inventor on its patented platform, brings that lived experience into his approach to building technology.</p></Reveal>
          <Reveal><p className="leading-relaxed text-muted-foreground">Military service, entrepreneurship, design, and cultural-heritage work inform how TopoStitch approaches stewardship, accessibility, and continuity of institutional knowledge. The aim is to preserve context around physical objects and places so knowledge can be understood, shared, and carried forward.</p></Reveal>
        </section>
        <section className="space-y-5"><Reveal><h2 className="text-2xl font-medium md:text-3xl">The recurring gap between capture and continuity</h2></Reveal><Reveal><p className="leading-relaxed text-muted-foreground">Capture and presentation technology continued to improve. Yet models lived in one place, metadata somewhere else. Source imagery, annotations, revisions, location data, and institutional knowledge could become separated across folders, platforms, teams, and projects.</p></Reveal><Reveal><p className="leading-relaxed text-muted-foreground">The resulting digital asset could be visually rich while its surrounding record remained fragmented. A new project or staff transition could make that knowledge harder to find and understand.</p></Reveal><Reveal><blockquote className="border-l-2 border-accent pl-6 text-xl leading-relaxed">What if the digital representation were not the end product, but part of a persistent record of the physical thing itself?</blockquote></Reveal><Reveal><p className="leading-relaxed text-muted-foreground">That question became the foundation for TopoStitch. We’re building around the identity of an object or place, connecting representations to evidence, provenance, location, relationships, interpretation, and history. Photographs, video, reports, condition records, capture details, and publishing or access information all belong in that broader product direction.</p></Reveal></section>
        <section className="space-y-5"><Reveal><h2 className="text-2xl font-medium md:text-3xl">A focused mission, an open learning process</h2></Reveal><Reveal><p className="leading-relaxed text-muted-foreground">Our mission is to preserve real-world knowledge for future generations. Cultural heritage is the first market we’re validating: museums, collections, archives, historic sites, preservation organizations, archaeological programs, universities with cultural collections, and related public-sector and nonprofit heritage organizations.</p></Reveal><Reveal><p className="leading-relaxed text-muted-foreground">TopoStitch is early-stage, in customer discovery, and building a working product. We’re investigating which gaps matter most to the professionals who steward these records. Their workflows will help determine what we build and how we evaluate it.</p></Reveal><Reveal><p className="leading-relaxed text-muted-foreground">Long-term stewardship means designing for continuity through new projects, technologies, platforms, staff transitions, and generations. Our sustainability philosophy centers on cultural memory, durable digital records, and reuse of existing documentation. It is an approach we’re developing and validating with the field.</p></Reveal><Link href="/platform" className="inline-flex min-h-11 items-center font-medium underline underline-offset-4">Explore the product direction →</Link></section>
      </div>
    </section>
    <Reveal amount={0.08}><Stewardship /></Reveal>
    <Reveal amount={0.08}><StartupVirginia /></Reveal>
    <Reveal amount={0.08}><CustomerDiscovery /></Reveal>
    <div aria-label="Company details" className="border-t border-border py-6">
      <Reveal><ul className="mx-auto flex max-w-6xl flex-wrap gap-x-6 gap-y-2 px-4 text-sm text-muted-foreground sm:px-6 lg:px-8">
        <li>Richmond, Virginia</li><li>Veteran-owned</li><li>Filipino American-owned</li><li>LGBTQ+-owned</li>
      </ul></Reveal>
    </div>
  </main><Footer /></>
}
